apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  labels:
    app: student-management
spec:
  selector:
    app: student-management
  ports:
    - protocol: TCP
      port: 80           # External port for the service
      targetPort: 8080   # Port your container exposes
  type: LoadBalancer    # Use NodePort for local clusters or ClusterIP for internal access
